In [3]:
import numpy as np

MyArray1 = np.arange(1, 20)
MyArray1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [4]:
MyArray2 = np.range(1, 20)  # 错误range（）是python中的内置函数不能在numpy中使用在numpy中要使用arange（）
MyArray2

AttributeError: module 'numpy' has no attribute 'range'

In [ ]:
list(range(1, 10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [ ]:
MyArray3 = np.array([1, 2, 3, 4, 5])
print(MyArray3)

[1 2 3 4 5]


In [ ]:
MyArray4 = np.array(range(0, 10))
MyArray4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
import numpy as np

MyArray5 = np.zeros(shape= (5, 5), dtype= np.float)
MyArray5

<ipython-input-2-235805d641ce>:3: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  MyArray5 = np.zeros(shape= (5, 5), dtype= np.float)


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
MyArray6 = np.ones(shape=(5, 5), dtype=np.int)
MyArray6

<ipython-input-3-a9e494887acc>:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  MyArray6 = np.ones(shape=(5, 5), dtype=np.int)


array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

#### 切片/读取

In [ ]:
import numpy as np

myArray = np.array(range(1, 10))
myArray

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
myArray[0]

1

In [ ]:
myArray[-1]

9

In [ ]:
print(myArray[::2])

[1 3 5 7 9]


In [ ]:
print(myArray[::-2])  # -2表示从末尾到第一个进行遍历并一两个单位

[9 7 5 3 1]


In [ ]:
print(myArray[1:2])

[2]


In [ ]:
print(myArray[[1, 6]])

[2 7]


In [ ]:
myArray[1:6]

array([2, 3, 4, 5, 6])

In [ ]:
myArray

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 规整化处理特征矩阵的方法

In [ ]:
myArray[:,np.newaxis]  # :表示选中所有

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [5]:
import random
rand = np.random.RandomState(32)
myArray1 = rand.randint(0, 100, (10, 10))
myArray1

array([[87, 43,  5, 54, 62, 88, 19, 71, 89,  3],
       [ 9,  4, 11, 81,  3, 65, 34, 35, 24, 42],
       [82, 10, 84, 50, 57, 69, 38, 77, 11, 62],
       [11, 90, 29, 52, 93, 90, 64, 11,  6, 94],
       [68, 62, 30, 80, 83, 50, 74, 35, 61, 50],
       [45, 24, 11, 93, 47, 43, 75, 50, 98, 68],
       [92, 48, 84, 82, 81, 59, 98, 80, 18, 78],
       [25, 70, 14, 61, 58, 51, 31,  0, 78, 53],
       [79,  1, 14, 19, 97, 76, 59,  7, 78, 70],
       [70, 98, 40, 17, 72, 89,  9, 82, 81, 95]])

In [6]:
myArray1[:, np.newaxis]

array([[[87, 43,  5, 54, 62, 88, 19, 71, 89,  3]],

       [[ 9,  4, 11, 81,  3, 65, 34, 35, 24, 42]],

       [[82, 10, 84, 50, 57, 69, 38, 77, 11, 62]],

       [[11, 90, 29, 52, 93, 90, 64, 11,  6, 94]],

       [[68, 62, 30, 80, 83, 50, 74, 35, 61, 50]],

       [[45, 24, 11, 93, 47, 43, 75, 50, 98, 68]],

       [[92, 48, 84, 82, 81, 59, 98, 80, 18, 78]],

       [[25, 70, 14, 61, 58, 51, 31,  0, 78, 53]],

       [[79,  1, 14, 19, 97, 76, 59,  7, 78, 70]],

       [[70, 98, 40, 17, 72, 89,  9, 82, 81, 95]]])

In [21]:
myArray1[:, np.newaxis].shape

(10, 1, 10)

In [24]:
myArray2 = np.arange(1, 21).reshape([5, 4])
myArray2
print(myArray2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [27]:
myArray2.shape
# myArray2.shape()  # 不能加（）

(5, 4)

In [22]:
myArray2[:, np.newaxis].shape

(5, 1, 4)

###### 多维数组的切片读取方法

In [28]:
myArray2[[2, 4], 3]

array([12, 20])