In [2]:
import os

print(os.path)

<module 'ntpath' from 'C:\\anaconda\\lib\\ntpath.py'>


#### 一次生成一个数

In [3]:
import random

random.seed(3)
random.randint(1, 100)  # 生成整数

31

In [4]:
import random

random.seed(3)
random.uniform(-10, 10)

-5.240707458162173

In [5]:
random.uniform?

In [6]:
random.seed(3)
round(random.uniform(-20, 20), 2)  # 保留两位位小数

-10.48

#### 一次随机生成一个随机数组

In [10]:
import numpy as np

rand = np.random.RandomState(32)  # 定义了一个随机变量的的生成器rand
x = rand.randint(0, 10, (3, 6))
x

array([[7, 5, 6, 8, 3, 7],
       [9, 3, 5, 9, 4, 1],
       [3, 1, 2, 3, 8, 2]])

In [13]:
import numpy as np

rand = np.random.RandomState(1)
x = rand.rand(1, 5) * 10  # rand.rand()的取值范围是[0, 1]
x

array([[4.17022005e+00, 7.20324493e+00, 1.14374817e-03, 3.02332573e+00,
        1.46755891e+00]])

In [2]:
import numpy as np

rand = np.random.RandomState(1)
x = rand.rand(2, 4) + 5
x

array([[5.417022  , 5.72032449, 5.00011437, 5.30233257],
       [5.14675589, 5.09233859, 5.18626021, 5.34556073]])

In [3]:
y = np.linspace(0, 10, 20)  # 生成一个有形状的矩阵
y

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])